# Generated by Django 4.2.3 on 2023-07-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_airports_passenger_alter_flight_arrival_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
