# Generated by Django 4.2.3 on 2023-07-06 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='ref_no',
        ),
    ]
