# Generated by Django 4.2.3 on 2023-07-08 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_tickets_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=8, unique=True)),
                ('passenger', models.CharField(max_length=50)),
                ('p_phone', models.CharField(max_length=15)),
                ('p_mail', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(default=None, max_length=6)),
                ('booking_date_time', models.DateTimeField(auto_now_add=True)),
                ('seat_number', models.IntegerField()),
                ('fare_charges', models.PositiveIntegerField()),
                ('status', models.CharField(default='CANCELED', max_length=20)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
