# Generated by Django 4.2.3 on 2023-07-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_airports_alter_flight_arrival_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='fare',
            field=models.PositiveIntegerField(default=1500),
        ),
    ]
