# Generated by Django 4.2.3 on 2023-07-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_booking_date_time_cancelledtickets_cancelled_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='seats_count',
            field=models.IntegerField(default=60),
        ),
    ]
