# Generated by Django 4.2.3 on 2023-07-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_flight_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='passenger',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=8),
        ),
    ]
