# Generated by Django 4.2.3 on 2023-07-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_tickets_age_tickets_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEMALE')], default='MALE', max_length=8),
        ),
    ]
