# Generated by Django 4.2.3 on 2023-07-07 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_tickets_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='age',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='gender',
        ),
    ]
