# Generated by Django 4.2.3 on 2023-07-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_passenger_age_remove_passenger_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='age',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='gender',
        ),
        migrations.AddField(
            model_name='passenger',
            name='age',
            field=models.IntegerField(default=20),
        ),
    ]
